theme: jekyll-theme-minimal
title: GitOps Workshop
description: Everything You Need To Become A GitOps Ninja
logo: https://avatars2.githubusercontent.com/u/56983333?s=400&u=1049feebdbd9c428e31d41140a130a0d59f860c2&v=4
